File editor crud
LandvibeDev/web-ide-front pull request #10
Opened 2020-08-13 06:59 UTC by kang-jisu

추가한거
redux-devtools-extension , json-server,material-icons

components/Body
-Explorer 
--FileTree 
--FileTreeTab 
 -Workspace 
--Editor 
--OpenFileTab
 --QuickIconTab
dialog
-CreateFIleDialog

기능 요약하면 이런느낌입니당..

redux에서는 openFiles, currentFile, directoryId 정보 저장
filetreetab에서 +누르면 새파일,새폴더 선택-> dialog열려서 추가 (생성 할 때 redux에 저장된 directoryId를 parentId로 삼음)
filetree에서 파일이나 폴더선택하면 currentFile,directoryId,openFiles 변경
openFileTab에 redux에 저장된 openFiles가져와서 보여주고 누르면 currentFile 변경시킴
currentFile에 대한 정보 받아와서 editor에 보여줌

기록남는거 수정했어용 ,,!!!! 이제 todo 추가해서 더 커밋할게요

2020-08-13 13:26 UTC, doyeongan commented
이거 작업중인거야? 아님 리뷰필요한거야?

2020-08-13 13:26 UTC, doyeongan commented
작업중인거면 pr 제목에 [WIP] 달아줘 * working in progress

2020-08-14 01:19 UTC, kang-jisu commented
아아 네 !! 아직 작업중이에요 !!

2020-08-18 08:07 UTC, kang-jisu commented
추가한 커밋 내용은 
원래 openFIles에 id,name만 저장했는데
- openfile 탭에 열어놓고 코드 수정하다가 저장은 안할수도 있을거같아서 파일 contents변경된거 openFIles에 같이 저장
- ctrl+s 누르면 아예 서버에 코드 저장
- 하이라이터 있는 코드에디터 
구현한거고
메뉴에 save눌렀을때 저장되게하기, 코드 수정하고 저장 안했을때 표시하기 정도 남았습니답

2020-08-18 13:54 UTC, doyeongan requested changes
지수 작업량 엄청나네 굿굿
정확히 어디까지 구현한 건지 몰라서 다 테스트는못해봤는데
몇개 에러로 보이는거 티켓 만들어서 올렸음

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/Dialog/CreateFileDialog.jsx
> +function CreateFileDialog({ type, open, handleClose, handleSubmit }) {
내생각엔
component/dialog/CreateFileDialog 가 되야할것같은데 어떻게 생각하니

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/Dialog/CreateFileDialog.jsx
> +  const [value, setValue] = useState('');
value is fileName?

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/Dialog/SaveAsDialog.jsx
> +function CreateFileDialog({ open, handleClose, handleSubmit }) {
이거 왜 중복?

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/WorkSpaceMain.jsx
> +    };
해당코드가 없으면 제대로 동작안하나?

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/components/Editor.jsx
> +            const data = document.querySelector('pre').innerText;
이건 체크해두었다가 좀더 좋은방법을 찾아보자

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/components/FileTreeTab.jsx
> +  const [fileDialogOpen, setFileDialogOpen] = useState(false);
isFileDialogOpen

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/components/MenuBar.jsx
> +  const [fileDialogOpen, setFileDialogOpen] = useState(false);
isFileDialogOpen

2020-08-18 13:54 UTC, doyeongan commented on src/workspace/components/MenuBar.jsx
> +  const [saveAsDialogOpen, setSaveAsDialogOpen] = useState(false);
isSaveAsDialogOpen

2020-08-19 03:47 UTC, kang-jisu commented on src/workspace/Dialog/CreateFileDialog.jsx
> +function CreateFileDialog({ type, open, handleClose, handleSubmit }) {
아 그러게요 ..!!!! 안에 넣어야겠어요

2020-08-19 03:48 UTC, kang-jisu commented on src/workspace/Dialog/CreateFileDialog.jsx
> +  const [value, setValue] = useState('');
아아아 네 textfield에서 입력하는 부분인데 앞으로 value같은거말고 의미담아서 이름지어야겠네욥 ㅎㅎ

2020-08-19 03:52 UTC, kang-jisu commented on src/workspace/Dialog/SaveAsDialog.jsx
> +function CreateFileDialog({ open, handleClose, handleSubmit }) {
save as 할때는 새로 만드는 파일 contents에 기존걸 담아주고 new file,folder일때는 빈 contents ('')로 생성하는데 그거 두개 다른구분지으려다보니깐 하나 더만들었는데,, 저도 거의 같은거 쓰려니깐 좀 찝찝했으여 ㅠㅠ 합쳐서 경우 나눌수없나 다시 생각해볼게요 !!

2020-08-19 03:57 UTC, kang-jisu commented on src/workspace/WorkSpaceMain.jsx
> +    };
워크스페이스부분에 라우팅이 아예 없어서 뒤로가기해버리면 너무 바로 자료가 날라갈거같아서,, ( 예를들면 저장 안하고 코드 변경하다 뒤로가기눌러버리면 대시보드로 돌아가면서 데이터는 지워지는??) 처리가 필요할거같아서 일단 넣어봤었어요 ,,,,! ㅎ ㅠ

2020-08-19 04:07 UTC, kang-jisu commented on src/workspace/Dialog/SaveAsDialog.jsx
> +function CreateFileDialog({ open, handleClose, handleSubmit }) {
오 심지어 컴포넌트이름도 안바꾸고 쓰고있었군 ..

2020-08-19 11:36 UTC, doyeongan approved these changes
LGTM
커멘트 남긴건 다음 PR에 반영해도되

2020-08-19 11:36 UTC, doyeongan commented on src/workspace/components/MenuBar.jsx
> +      } else deleteFile(selectedId);
if 가 점점많아지는데 switch 문으로 바꿔보는건어떰?

2020-08-19 12:03 UTC, kang-jisu commented on src/workspace/components/MenuBar.jsx
> +      } else deleteFile(selectedId);
아하~ 반영할게욧ㅎㅎ
감사합니당!!!!

2020-08-19 12:04 UTC, merged