Workspace
LandvibeDev/web-ide-front pull request #5
Opened 2020-08-07 13:34 UTC by kang-jisu

새로 깐거 '@material-ui/lab';

WorkSpaceMain->Header
                               Body
                               Terminal이렇게나누고
Header에 
     - 로고
     - HeaderMenuList(파일,편집,프로젝트 메뉴 부분)
           -HeaderMenuBtn 
Body
       -fileTree 
                    -fileTab(새파일,새로고침)
                    -fileTreeView (폴더구조view)
       -codeEditor
                     -열려있는 파일 tab 
                     -codeEditorView (소스코드 view) 
Terminal 
       -Command   run,build,custom 명령어들 
       -TerminalBody 실제 터미널 창 

일단 이런식으로 놔두고,, fileTreeView에서 파일 선택하면 codeEditor에서 보여져야돼서 리덕스로 선택한 파일 가져오는거 설정해봤는데
열려있는 파일 여러개로 만들고 처리하려면,, 어떻게해야할지는 감이 잘 안잡히네욥..ㅎ ㅠㅠㅠ
그냥 메테리얼에있는 기능 가져다 모양만 잡았습니답 .. ㅠ-ㅠ

2020-08-07 15:09 UTC, doyeongan requested changes
짧은시간내에 많은 코드를 작성한거에 칭찬을!
열심히했네 
그런데 많은코드를 짧은시간내에 쓰다보니 naming 고려가 조금 부족한거 같다
그분 중점적으로 다시 생각해서 patch 올려줘~

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/Body.jsx
> +function Body(props) {
naming 이 살짝 애매한데

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/Terminal.jsx
> +        <Command />
Terminal인데 Command?

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/containers/CurrentFileContainer.jsx
> +function CurrentFileContainer() {
왜 얘만 containers 에 있는지 설명부탁

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/CodeEditor.jsx
> +// function a11yProps(index) {
나중에 사용할 코드가 아니면 삭제

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/FileTreeView.jsx
> +// redux 실험중
추후 작업이 필요한곳에 comment 남길때는
// TODO: redux 실험중

이런식으로~

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/FileTreeView.jsx
> +  //   const onClearFile = () => dispatch(clearFile());
나중에 사용할 코드가 아니면 삭제

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/FileTreeView.jsx
> +  //   const onClearFile = () => dispatch(clearFile());
아 워닝때매 주석처리한건가 ㅎㅎ?그럼일단무시..

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/HeaderMenuBtn.jsx
> +function HeaderMenuBtn(props) {
굳이 prefix 로 header 붙일필요없음

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/HeaderMenuList.jsx
> +function HeaderMenuList(props) {
MenuBar 
정도가 더 좋을듯

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/TerminalBody.jsx
> +function TerminalBody(props) {
Terminal
ㄴ TerminalBody
ㄴ Command

왜 Terminal 밑에 command가 있는지모르겠고
TerminalBody가 사실 Terminal인거같은데 Terminal, TerminalBody naming 다시고려

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/FileTree.jsx
> +      <FileTab />
FileTree
ㄴ FileTreeView
ㄴ FileTab

직관적으로보기엔 FileTreeView 가 더 상위컴포넌트 이름으로 느껴지는데 어떻게 생각하니

2020-08-07 15:09 UTC, doyeongan commented on src/workspace/components/Command.jsx
> +function Command(props) {
이것도 naming 다시고려

2020-08-07 15:24 UTC, doyeongan commented
- redux 는 일단 컴포넌트 구조잡고 다시생각해보는걸로
- app.js 충돌나는건 숙제로해결해오기!

2020-08-07 16:40 UTC, kang-jisu commented on src/workspace/components/Body.jsx
> +function Body(props) {
헷.. 이름들 다시 고민해볼게요!!!!

2020-08-07 16:47 UTC, kang-jisu commented on src/workspace/containers/CurrentFileContainer.jsx
> +function CurrentFileContainer() {
지원이 redux했을때 구조 보고 modules/containers/components 폴더 나눈거였는데
` const { name, openFiles } = useSelector((state) => ({
    name: state.currentFileName,
    openFiles: state.openFiles,
  }));`
CodeEditor 컴포넌트에서 바로 useSelector로 받아온 값 써보려니깐 name,openFiles이런애들을 못읽어오더라구요,,,?ㅠ 그래서 컨ㄴ테이너로 감싸고 하위컴포넌트로 값 보내주는식으로 써야되는건가 해서 이렇게 만들어봤는데 ,,

2020-08-07 16:49 UTC, kang-jisu commented
전체적으로 이름 좀 바꿔볼게욥 ㅎ--ㅎ

2020-08-08 05:53 UTC, kang-jisu commented
Header에                                                        < 지금 바꿔본 이름 >
- 로고                                                                     Header
- HeaderMenuList(파일,편집,프로젝트 메뉴 부분)     - MenuBar
-HeaderMenuBtn                                                    - MenuBtn
Body                                                                    MainContainer
-fileTree                                                                    - LeftSideBar  <<- fileTreeNavBar 뭐 이런거로 할까도 새각했는데,, 
-fileTab(새파일,새로고침)                                                    - fileTab
-fileTreeView (폴더구조view)                                             - fileTreeView
-codeEditor                                                               -CodeEditor
-열려있는 파일 tab
-codeEditorView (소스코드 view)                                     -CodeEditorView
Terminal                                                              BottomContainer
-Command run,build,custom 명령어들                      - Command <<- 아니면 CommandList..??
-TerminalBody 실제 터미널 창                                     - Terminal

이름..고민입니당..ㅠ-ㅠ

2020-08-08 05:56 UTC, doyeongan commented
> Header에 < 지금 바꿔본 이름 >
> 
> * 로고                                                                     Header
> * HeaderMenuList(파일,편집,프로젝트 메뉴 부분)     - MenuBar
>   -HeaderMenuBtn                                                    - MenuBtn
>   Body                                                                    MainContainer
>   -fileTree                                                                    - LeftSideBar  <<- fileTreeNavBar 뭐 이런거로 할까도 새각했는데,,
>   -fileTab(새파일,새로고침)                                                    - fileTab
>   -fileTreeView (폴더구조view)                                             - fileTreeView
>   -codeEditor                                                               -CodeEditor
>   -열려있는 파일 tab
>   -codeEditorView (소스코드 view)                                     -CodeEditorView
>   Terminal                                                              BottomContainer
>   -Command run,build,custom 명령어들                      - Command <<- 아니면 CommandList..??
>   -TerminalBody 실제 터미널 창                                     - Terminal
> 
> 이름..고민입니당..ㅠ-ㅠ

2020-08-08 06:06 UTC, doyeongan commented
> Header에 < 지금 바꿔본 이름 >
> 
> * 로고                                                                     Header
> * HeaderMenuList(파일,편집,프로젝트 메뉴 부분)     - MenuBar
>   -HeaderMenuBtn                                                    - MenuBtn
>   Body                                                                    MainContainer
>   -fileTree                                                                    - LeftSideBar  <<- fileTreeNavBar 뭐 이런거로 할까도 새각했는데,,
>   -fileTab(새파일,새로고침)                                                    - fileTab
>   -fileTreeView (폴더구조view)                                             - fileTreeView
>   -codeEditor                                                               -CodeEditor
>   -열려있는 파일 tab
>   -codeEditorView (소스코드 view)                                     -CodeEditorView
>   Terminal                                                              BottomContainer
>   -Command run,build,custom 명령어들                      - Command <<- 아니면 CommandList..??
>   -TerminalBody 실제 터미널 창                                     - Terminal
> 
> 이름..고민입니당..ㅠ-ㅠ

Header
-MenuBar
--MenuItem

Body
-Workspace
--Editor(CodeEditorView)
--OpenFileTab(열려있는 파일 tab)

-Explorer
--fileTree (fileTreeView)
--fileTreeTab
--CommandList

-Panel or BottomPanel
--Terminal

요런 구조는 어떨까 의견제시 바랍니다.

2020-08-08 06:11 UTC, kang-jisu commented
아 ! Explorer에 파일이랑 커맨드 합치는방식이 맞는거같아요 ㅠ 
참고해서 다시 만들고 커밋하겠습니답!!

2020-08-08 10:08 UTC, kang-jisu commented
@material-ui/icons 설치
Header
-MenuBar
-MenuBtn->MenuItem

Body
-Workspace
--Editor
--OpenFileTab
--QuickIconTab (원래 openfiletab에 있었는데 따로 분리함)

-Explorer
--FileTree
--FileTreeTab
--CommandList
---CommandItem

-BottomPanel
--Terminal
---OutputLog
---InputPrompt

이렇게 바꾸고 commandlist는  table ui써서 item은 따로 뺐구요
터미널은 입력하면 outputlog에 추가돼서 보여지는식으로 대충 모양만 잡아봤어요
이름도 이런식으로 하는게 맞을지,, 잘모르겠네용 ㅠ-ㅠ 터미널 용어가 헷갈려서ㅠㅠㅠ
outputLog 는 TerminalLog..? script..? 
inputPrompt도 inputForm이나 commandline ..? 뭐 몇개 생각해봤었는데 @_@추천부탁드립니다 .,..

2020-08-08 10:20 UTC, doyeongan commented
> @material-ui/icons 설치
> Header
> -MenuBar
> -MenuBtn->MenuItem ( 로고는 원래 div 울림ide /div 이런식으로 했다가 MenuItem에 넣어버렸어요 )
> 
> Body
> -Workspace
> --Editor
> --OpenFileTab
> --QuickIconTab (원래 openfiletab에 있었는데 따로 분리함)
> 
> -Explorer
> --FileTree
> --FileTreeTab
> --CommandList
> ---CommandItem
> 
> -BottomPanel
> --Terminal
> ---OutputLog
> ---InputPrompt
> 
> 이렇게 바꾸고 commandlist는 table ui써서 item은 따로 뺐구요
> 터미널은 입력하면 outputlog에 추가돼서 보여지는식으로 대충 모양만 잡아봤어요
> 이름도 이런식으로 하는게 맞을지,, 잘모르겠네용 ㅠ-ㅠ 터미널 용어가 헷갈려서ㅠㅠㅠ
> outputLog 는 TerminalLog..? script..?
> inputPrompt도 inputForm이나 commandline ..? 뭐 몇개 생각해봤었는데 @_@추천부탁드립니다 .,..

InputPrompt
OutputPrompt
로 하면 괜찮을듯
일단 이렇게 진행하고 터미널 구조는 나중에 한번다시 살펴보자

오늘 폭풍 코딩하네 고생많아~

2020-08-08 10:23 UTC, kang-jisu commented
넵 !! 😁

2020-08-08 10:31 UTC, doyeongan commented
LGTM!!

근데, 왜 빌드가 안돌지..흠
일단 이번 PR 리뷰는 이정도로하고
App.js 충돌 방안 해결해오면 approve 할께

2020-08-08 10:34 UTC, doyeongan approved these changes

2020-08-08 10:35 UTC, doyeongan requested changes

2020-08-08 10:35 UTC, doyeongan commented on src/App.js
>  function App() {
resolve 필요

2020-08-09 10:00 UTC, doyeongan approved these changes
LGTM
지수 수고많았어~
리뷰 받으면서 작업해본 소감이?
공동으로 작업해야할부분이기도하고 제일 중요한 부분이라 좀 빡세게봤던거같음

2020-08-09 10:01 UTC, doyeongan commented
아 반영은 squash and merge 로 부탁

2020-08-09 10:08 UTC, kang-jisu commented
오예 드디어 ~~~~~~~
pr도그렇고 코드별로 리뷰받아본게 처음이라 넘 신기했어여 ,, ㅋㅋㅋㅋ >< 기능은 나중에 바꾸더라도 컴포넌트 구조랑 이름은 미리 진짜 잘 정해두고 시작하는게 좋은거같아서,,  앞으로도 이번에 고민한것들 잘 참고해야겠어요 !_! bb

2020-08-09 10:08 UTC, kang-jisu commented
merge workpspace pull request

2020-08-09 10:09 UTC, merged