signin first push
LandvibeDev/web-ide-front pull request #7
Opened 2020-08-08 13:03 UTC by gjm1026

http://localhost:3000/signin
http://localhost:3000/signup

yarn add react-google-login
yarn add react-github-login
npm install --save react-github-login-button

<signin/components/Logo.jsx>
일단 logo로 함

<signin/components/SignIn.jsx>
email과 password를 통해 로그인할 시 필수로 값을 입력하도록 처리
구글 OAuth 인증으로 client id 발급받아서 'react-google-login' 적용함
깃허브 OAuth 인증으로 client id 발급받아서 'react-github-login' 적용했는데 구글처럼 바로 로그인 페이지가 뜰 줄 알았는데 깃허브는 좀 달라서 아직 이해를 제대로 하지 못했다 

<signin/components/SignUp.jsx>
인풋 값들을 필수로 입력하도록 하였고 체크박스로 이용약관 동의 검사 적용함
github API 사용하는 부분은 좀 어려운점이 있어서 설계서도 보면서 해봐야할 것 같다..
구글 로그인 했을 때 로그아웃이 되는지 테스트하기 위해 구글 로그아웃 추가

구글 로그인 때문에 warning이 많이 뜨는데 아직 해결못했씁니다 천천히 없애도록 할게여

2020-08-08 13:25 UTC, doyeongan requested changes
OAuth 관련해서 이정도까지 해올줄몰랐는데 많이 했네
칭찬해~
다만 리뷰지적한 부분 다시보고 패치 부탁!

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/Logo.jsx
> +function Logo(props) {
이런건 common 으로

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignIn.jsx
> +        <TextField
쏘리...
내가 문서 업데이트한단걸까먹음
사실 여기서 email/pw 치는 부분이 없어져야함
OAuth login 할꺼기때문

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignIn.jsx
> +  const googleClientId =
이런 값들은 json 형태로 저장해서 환경변수 처럼 사용하면 좋음
일단이번 리뷰에선 패스

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignIn.jsx
> +          redirectUri="http://localhost:3000/signup"
uri 상수변수로 분리

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignUp.jsx
> +  const [term, setTerm] = useState(false);
term 만 하면 헷갈리니
IsTermChecked 정도가 좋을듯

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignUp.jsx
> +  const [termError, setTermError] = useState(false);
위에 변수랑 분리해서 사용하는 이유 설명부탁

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignUp.jsx
> +    setTerm(!term);
오류가생길수있는 코드
실제 체크박스의 value 를 가져와서 사용하는게 좋다

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignUp.jsx
> +              label="nickname"
밑에도그렇고 string은 문서에있는거 그대로쓰지말고 적당히 만들어 넣어라~(한글)

2020-08-08 13:25 UTC, doyeongan commented on src/signin/components/SignUp.jsx
> +              SIGN IN
SIGN UP

2020-08-08 13:25 UTC, doyeongan commented on src/signin/view/SignInView.jsx
> +function SignInView(props) {
View 보다는 container 로 통일하는게 좋겠음

2020-08-08 13:28 UTC, doyeongan commented
아 그리고 로컬작업할때도 커밋 쪼개서 하는걸 추천...

2020-08-08 13:47 UTC, gjm1026 commented
확인했씁니다!!

2020-08-09 13:35 UTC, doyeongan commented on src/signin/view/SignInView.jsx
> +function SignInView(props) {
@gjm1026  이거 반영안되어있는거같은데
View로 하고싶으면 반대의견내고 진행해도됨

2020-08-09 13:36 UTC, doyeongan commented on src/signin/view/SignInView.jsx
> +function SignInView(props) {
아 경로만 바뀌고 component name 은 그대로네

2020-08-09 14:31 UTC, doyeongan commented
LGTM
막판에 merge conflict 해결하느라 수고많았다 👍 
현업으로가면 conflict 맨날난다 좋은 경험했길...

2020-08-09 14:32 UTC, doyeongan commented
merge는 squash and merge 로 부탁

2020-08-09 14:34 UTC, gjm1026 commented
ㅎ ㅏ 약간쓰 힘드네요 저 잠깐 더 봐야할게 있는거같아서 그거만 좀 수정할게요

2020-08-09 14:36 UTC, doyeongan commented
일단 이거는 merge 하고 그건 새로 pr만들어서 올리는게 좋을듯?
이거 너무길어지면 힘들어

2020-08-09 14:37 UTC, doyeongan commented
그리고 아까도 말했듯이 pr merge 되면 사용했던 브랜치는 재사용하지않고
master에서 새로 브랜치 따서 사용
사용하던 브랜치 삭제하면 센스굿

2020-08-09 14:40 UTC, gjm1026 commented on src/signin/view/SignInView.jsx
> +function SignInView(props) {
와이거이제확인했네

2020-08-09 14:40 UTC, gjm1026 commented on src/signin/view/SignInView.jsx
> +function SignInView(props) {
딱히 반대는 아니었어요..

2020-08-09 14:41 UTC, gjm1026 commented
그 체크박스 유효성검사 부분에서 수정할게있는데 그냥 새로 올릴까요?

2020-08-09 15:52 UTC, kang-jisu commented
리뷰가필요한가

2020-08-09 15:53 UTC, gjm1026 commented
정말 마지막입니다 ㅜㅜ 체크박스 유효성 검사하는 부분에서 살짝의 오류가 있는 것 발견하고 수정하였어요 
체크박스 상태를 담는 변수가 하나 더 필요할 것 같아서 termError 추가했구요

2020-08-09 15:53 UTC, kang-jisu commented
리뷰달면 머지할수있을줄알고 달았는데 나는 권한이 아닌가봐,,>.<

2020-08-09 15:54 UTC, gjm1026 commented
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ >< 나도 빨리하고싶다!!!

2020-08-10 04:46 UTC, doyeongan approved these changes
approve 후에 수정이있어서 다시 approve 가 필요한거임 이제 머지 될꺼~

2020-08-10 04:47 UTC, doyeongan commented
> 리뷰달면 머지할수있을줄알고 달았는데 나는 권한이 아닌가봐,,>.<

지수도 권한있을껄?

2020-08-10 05:25 UTC, KeonHee approved these changes
LGTM👍

2020-08-10 06:07 UTC, merged